### PR TITLE
Proposal: Docker demo

### PR DESCRIPTION
**Pull request by grischa**
We believe MyTardis should come with a default deployment method, and it should be based on Docker.
This will not disable other deployment methods, it will just become the suggested way.
The current suggested way is presented in the installation docs without exhaustively providing instructions on all possible ways of installing MyTardis. This PR is the first step, providing a demo/test environment based on Docker.

Having a continuously integrated Docker deployment and images on docker hub has a number of advantages:

Effective continuous integration
- Can make and test modular containers, e.g. excluding and including optional apps
- Can test against different database backends locally and in the CI

Community maintained deployment method
- New users encounter a controlled environment, easier to help with issues
- dependencies including the host OS (Docker’s FROM) etc are upgraded via pull request and after testing, no surprises when deploying

Encourages elastic deployments

Arguments for separate build and run containers: size
Naming can be discussed, i.e. should it by `mytardis` or `mytardis-run`

With more thorough testing this can become part of a continuous deployment pipeline.

Instructions for this PR:

`docker-compose up` will work once these images have been pushed to Docker hub.
To test now, build them locally with:
`docker-compose -f docker-build.yml build && docker-compose -f docker-build.yml run builder && docker-compose -f docker-test.yml build` and then `docker-compose up`

### CODE REVIEW

**Comment by pansapiens** [comment]
This looks really promising. Here's a list of tweaks I would make.

SFTP fails to come up with a `socket.error: [Errno 99] Cannot assign requested address` - you are probably already aware of this.

I like the use of `env_settings.py` - good step toward becoming a 12-factor app and will generally support containerisation. The database environment variables could be simplified by using [dj-database-url](https://github.com/kennethreitz/dj-database-url).

Not sure if there is a strong convention for this but I'd prefer some (mostly cosmetic) reorganisation if it doesn't complicate running the Compose stack too much. I'd move the `Dockerfile*`'s, the `scripts` folder and `docker_demo.env` into a `Docker` folder. Seems like too much stuff dumped in the root folder right now and it would be advantageous to keep all the Docker specific stuff in one place.

`test_on_mysql_settings.py` and `test_on_postgresql_settings.py` could probably consolidated somehow (`dj-database-url` would also help here). Since they only seem to be used for `./test.sh`, these settings could probably just be passed in as environment variables in that file.

`tests.sh` has some issues (at least on the MacOS version of bash) - variables on lines 3, 20 and 23 inside if statements are missing a `$`. In most cases it's also safest to double quote these variables like `"${EXTRA_REQS}"` (I'm no bash expert, but I run [shellcheck](https://github.com/koalaman/shellcheck )- seperate issue but it would be good if this could be run as a standard linter on Codacy).

**Comment by grischa** [comment]
Thanks @pansapiens I'll update this soon with your feedback

**Comment by pansapiens** [comment]
Since this PR has stalled and there was no consensus on including Dockerfiles in the main repo, I suggest it should be split into two parts:

1) a new PR for the 12factor-ization / refactoring of settings (which is really independent of Docker and a valuable improvement)

2) a new repo `mytardis-docker` containing just the Docker, Compose and associated config files and helper scripts. The main `mytardis` repo could be pulled in as a git submodule [[example](https://github.com/ryanfb/tesseract_latinocr_docker)] (or the `mytardis-docker` repo pulled in as a submodule in a `mytardis` working copy ?). Irrespective there would probably need to be some modification to the paths used in the Docker setup to streamline this.

**Comment by grischa** [comment]
Closing this. Going to implement Docker support in a different way after all, outside of the mytardis repo. I'll post updates when I have something to show

**Pull request closed without merging**
