### PR TITLE
transitioned squashed migration to normal migration

### PR DESCRIPTION
**Pull request by grischa**
If anyone needs to redo older migrations, they just have to checkout an older version first, migrate, then checkout this version

### CODE REVIEW

**Comment by nrmay** [comment]
This could cause complications for us.
Why is this required now?

**Comment by nrmay** [comment]
I don't think you need to delete the other files. 
When Django runs migrate, it looks for squash files and runs them instead of the original. 
Unless you are part way through the list and then it will run the individual migration files as required.

**Comment by grischa** [comment]
@nrmay What kind of complications?
It isn't strictly required, but it would be sensible to complete the squashing so that new migrations can be added with less naming confusion.
See bottom of this paragraph https://docs.djangoproject.com/en/1.8/topics/migrations/#squashing-migrations

I thought your installations require the squashed migration over the individual ones, that's why you squashed them?

**Comment by nrmay** [comment]
We have deployments on branches that are part way along. So, we'd need to upgrade these before you delete the old migration files. Note, from the reference above: 

>You should commit this migration but leave the old ones in place;
> the new migration will be used for new installs. Once you are sure
> all instances of the codebase have applied the migrations you squashed,
> you can delete them.

**A suggestion**: this operation should be done once, and as the final pull request, for each version release.

**Comment by grischa** [comment]
Sure, we can do this with a version release, that will be less surprising

**Pull request closed without merging**
