### PR TITLE
Automatically looks in installed Tardis apps for an api module,

### PR DESCRIPTION
**Pull request by wettenhj**
containing additions to the RESTful API in the form of classes
ending with "AppResource".

### CODE REVIEW

**Comment by wettenhj** [comment]
An implementation of Grischa's proposal in Trello for additions to the API: https://trello.com/c/NIlUjmkN/8-investigate-moving-mydata-s-mytardis-data-models-into-a-separate-app

**Comment by grischa** [comment]
Thanks @wettenhj
Don't worry about fixing this, I already thought of how to do it and I'll have it done this afternoon

**Comment by wettenhj** [comment]
Ok, no worries.  I thought you might have a specific way you wanted to implement this.  But I just wanted to get something up and running to test the "mydata" app against for now, and I thought I may as well share it with you via a pull request.  The "AppResource" matching method seems to work well, except that you need to explicitly define the resource_name, to avoid unintentionally including "app" in the URL, e.g. "/api/v1/modelapp/1/".  Are you happy with apps sharing the same API URI namespace as tardis_portal?  Or would you prefer Tardis apps to use their own URI namespace, e.g. "/app/mydata/api/v1/model/1"?

**Comment by grischa** [comment]
I thought it best to prefix the api calls with the app name.
It only works for Tastypie Resources, so the `/api/v1` prefix seems sensible

**Pull request closed without merging**
