### PR TITLE
Switch to installing `psycopg2-binary` via pip

### PR DESCRIPTION
**Pull request by keithschulze**
Removes dependency on system package for `psycopg2` for Ubuntu

Upgrades to version 2.7.4

### CODE REVIEW

**Comment by wettenhj** [comment]
Thanks @keithschulze.

Can you please remove postgresql-server-dev-all and psycopg2 from Dockerfile-build too?

**Comment by keithschulze** [comment]
Good catch @wettenhj. I have removed them.

**Comment by wettenhj** [comment]
I suggest moving ```psycopg2-binary==2.7.4``` to a new ```requirements-postgres.txt``` (as done in the Django 1.11 branch).

Then in Dockerfile-test, you would need to add:
```
RUN . /appenv/bin/activate; \
    pip install --no-index -f /wheelhouse -r requirements-postgres.txt
```

In the Django1.11 branch, I've added the above to Dockerfile-test just before the "pip install" for coveralls and codacy.

You could also add ```pip wheel -r requirements-postgres.txt; \``` to ```Dockerfile-build```, so it goes into the wheelhouse, but it might not be necessary, because a binary wheel is available.

**Comment by wettenhj** [comment]
To be clear, in the Django 1.11 branch, I currently do the ```pip wheel -r requirements-postgres.txt; \``` in ```Dockerfile-build```, probably not because we need to build a wheel from source (as we do for MySQL-python), but just to be consistent with MySQL-python, so both have a wheel in our wheelhouse.  If you avoid adding wheel(s) to our wheelhouse for requirements-postgres.txt in the ```Dockerfile-build``` step, then you would probably need to change the ```pip install --no-index -f /wheelhouse -r requirements-postgres.txt``` command in ```Dockerfile-test``` to ```pip install -r requirements-postgres.txt```

**Comment by wettenhj** [comment]
Thanks!

**Pull request merged**
