### PR TITLE
Make Parameter.set_value handle LINK data_types

### PR DESCRIPTION
**Pull request by pansapiens**
Currently Parameter.set_value doesn't explicitly handle LINK data_types, which means the REST API can't be used to properly fill all required fields (link_ct / linkid) for this Parameter type.

This patch makes Parameter.set_value for LINKs correctly assign the link_ct / link_id (from which link.gfk GenericForeignKey is derived) for standard experiment and dataset link URLs (like those returned by the API, and Experiment or Dataset get_absolute_url() ). This makes the API for setting link parameters consistent with other parts of the API, since the URL path in the 'Location' header field returned by the REST API when creating a new experiment or dataset can be used to directly when setting a link parameter. The string_value is always set and can be used as a fallback when link_gfk isn't set.

I'm not entirely satisfied with the method of matching urls in the Parameter value, but I haven't found a good way to map get_absolute_url()'s back to their associated model, and the current method will cover the two most likely use cases (which I'm currently using in a MyTardis app).

I've also made Parameter.link_url aware of DATAFILE_VIEWS, DATASET_VIEWS and EXPERIMENT_VIEWS view override methods defined in settings.

### CODE REVIEW

**Comment by pansapiens** [comment]
Aware that some tests aren't passing. I'll continue to work on this to figure out why.

**Comment by omgwtfgames** [comment]
Tests now pass. Rebased onto current develop. Added some general tests for the Dataset model in process - in particular there was nothing to exercise Dataset.get_absolute_url().

**Comment by pansapiens** [comment]
I've now removed the unnecessary code related to view overrides. I also simplified the URL parsing code, dealt with absence/presence of trailing slashes.

Added support for parsing /v1/api/experiment/<id> and  /v1/api/dataset/<id> URLs (as returned by the API upon object creation).

**Comment by pansapiens** [comment]
Just made this merge-able after the changes to views on develop. I think I've made your suggested changes @grischa - is there more to do ?

**Comment by grischa** [comment]
Replaced by #577

**Pull request closed without merging**
