### PR TITLE
(i) File size calculation in _compute_checksums() doesn't work and is…

### PR DESCRIPTION
**Pull request by wettenhj**
… unnecessary.

      Running "update_fns[key](results[key], chunk)" evaluates
      "lambda x, y: x + len(y)" which calculates the cumulative size, but
      then the cumulative size isn't saved anywhere, i.e. results['size'] remains
      equal to zero.  Also, calling _compute_checksums resulted in an integer
      (not string) size being recorded in "actual", which could cause
      val != database[key] to log a size mismatch because of the int/string mismatch.

(ii) In verify(), surely "if not settings.REQUIRE_DATAFILE_SIZES:" is meant to be
       "if settings.REQUIRE_DATAFILE_SIZES:"?  Otherwise, how can verify()
       ever use 'size' in "error_message += ' %s did not match.' % key"?
       This would require the 'size' key to be in actual, which would require
       it to be in database, so it would only be possible to see
       the " size did not match." error message when REQUIRE_DATAFILE_SIZES is False.

(iii)  If the file to be verified doesn't exist yet (or can't be accessed), an IOError
        will be raised, and the values within actual will not change from their initial
        values (None).  Then the error_message logged will include things like
        " md5sum did not match.".  I think it's clearer to just to put the IOError
        message in the error log.  I'm actually wondering whether this should be a
        warning, not an error for the case where the IOError's errno is errno.ENOENT
        (file doesn't exist yet).  Because a critical error shouldn't be raised just
        because a client waits a second or two between creating the datafile record
        and uploading the datafile.

### CODE REVIEW

**Comment by wettenhj** [comment]
I committed a workaround for one of the two Semaphore build errors (failed tests), but then I removed that commit, because the failed test actually has nothing to do with the changes I'm committing.  The first failed test is tardis.tardis_portal.tests.test_views.UploadTestCase.testFileUpload which assumes that local files will be auto-verified immediately, whereas now there is a 5 second delay: https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/hooks.py#L83

**Comment by grischa** [comment]
Thanks for adding the IO Error message logic. It was on my to do list as well.
However, you still need to figure out why the tests fail. The current develop branch passes, so it must be something in your changes.

**Comment by wettenhj** [comment]
Hmm, so far I can't reproduce the errors Semaphore is getting when I run the tests on my MyTardis test VM, using this "dfo-verify-size-checks" branch.  The only errors I'm getting are:

ERROR: testGetRecord (tardis.apps.anzsrc_codes.tests.test_oai.EndpointTestCase)
ERROR: testListIdentifiers (tardis.apps.anzsrc_codes.tests.test_oai.EndpointTestCase)
ERROR: testListRecords (tardis.apps.anzsrc_codes.tests.test_oai.EndpointTestCase)

**Comment by wettenhj** [comment]
Oops, I was just grepping the test results for ERROR, not FAILED.  I can reproduce the Semaphore errors with that branch.

**Comment by grischa** [comment]
I caught the error now, just reworking it a bit then I'll push the fix

**Comment by wettenhj** [comment]
Ah yes, I see the error now.  Somehow size is still being recorded as an integer, not a string, which raises this error:

Traceback (most recent call last):
  File "/opt/mytardis/develop/tardis/tardis_portal/models/datafile.py", line 569, in verify
    database[key].strip() != '' \
AttributeError: 'int' object has no attribute 'strip'

**Comment by wettenhj** [comment]
Not commtting, because @grischa says he will push a fix.  But the following changes would remove the Semaphore build errors:

```
--- a/tardis/tardis_portal/views.py
+++ b/tardis/tardis_portal/views.py
@@ -2727,7 +2727,7 @@ def upload(request, dataset_id):
                 uploaded_file_post)
             datafile = DataFile(dataset=dataset,
                                 filename=uploaded_file_post.name,
-                                size=uploaded_file_post.size,
+                                size=str(uploaded_file_post.size),
                                 md5sum=md5,
                                 sha512sum=sha512)
             datafile.save(require_checksums=False)
```
```
--- a/tardis/tardis_portal/tests/filters/test_middleware.py
+++ b/tardis/tardis_portal/tests/filters/test_middleware.py
@@ -86,7 +86,7 @@ class FilterInitTestCase(TestCase):
 
             datafile = DataFile(dataset=dataset,
                                 filename=path.basename(testfile),
-                                size=size,
+                                size=str(size),
                                 sha512sum=sha512sum)
             datafile.save()
             dfo = DataFileObject(
```

**Comment by grischa** [comment]
Thanks, James.
I changed it quite a bit again, and fixed the str/int bug in the save method now.

**Pull request merged**
