### PR TITLE
Add Facility, Instrument to Experiment, Dataset views

### PR DESCRIPTION
**Pull request by avrljk**
Includes changes to these views in addition to the regular MyTardis views:
    tardis/apps/mx_views/views.py
    tardis/apps/slideshow_view/views.py

### CODE REVIEW

**Comment by keithschulze** [comment]
Sorry for my slow response and thanks again for submitting the PR -- this is a very valuable change.

Unfortunately, the PR has failed the SemaphoreCI check because a few of the unit tests are failing as a result of your changes. The failures arise because the changes in several places assume that `instrument` field is set for a dataset; however, setting an instrument for a dataset is in fact optional.  Thus, you will need to be a bit more defensive in accessing the `instrument` field i.e., check whether it return `None`.

As a side note, you should be able to run these tests locally in your dev environment using the test.py script in the base mytardis directory e.g.:

```
bash$ cd /path/to/mytardis
bash$ source /path/to/mytardis/virtualenv/bin/activate
(mytardis) bash$ ./test.py
nosetests --verbosity=1
Creating test database for alias 'default'...

....................................................................
..............................................S.S.S.S.S.S.S.........
............S................E..........E....S.S.S.S.S...S..E.......
.........
====================================================================
==
ERROR: testDatasetJson (tardis.tardis_portal.tests.test_views.Experi
mentTestCase)
--------------------------------------------------------------------
--
...
```

**Comment by avrljk** [comment]
Thanks for the feedback.  I should have realised other site's deployments might have different policies re. Datasets without Instruments.  I'll prepare fix early next week.

I'd love to run the tests, but the local development environment I've been given doesn't yet support them (I'll keep asking). I'll find another way to do the testing if I don't hear anything by the time the fix is ready.

**Comment by keithschulze** [comment]
@avrljk￼, your new changes look good to me and I've done some testing to verify things work as expected here. 

Testing the `mx_views` and `slideshow_view` code is more tricky as we aren't actively using those apps here. I suspect the`view_full_dataset` methods in views.py of those apps will run into the same issues accessing instrument/facility attributes. That said, given it's not so easy to test and that having instrument/facility shown to those specific views is probably not essential at this point, I think it may be easiest if you just revert the changes you made in those apps. What do you think?

**Comment by keithschulze** [comment]
Thanks @avrljk!

**Pull request merged**
