### PR TITLE
Sftpd logging

### PR DESCRIPTION
**Pull request by wettenhj**
I'm interesting in knowing what IP addresses are probing port 2200 on my MyTardis server, so I've added some more logging to sftp.py.

Here's an example (where I've replaced my IP address with 1.2.3.4, and I've replaced Nagios's IP address with 5.6.7.8):

```
2015-08-21 10:22:31,480 - INFO - Connection requested from 1.2.3.4
2015-08-21 10:22:31,528 - INFO - Connected (version 2.0, client OpenSSH_6.2)
2015-08-21 10:22:31,972 - INFO - Auth rejected (none).
2015-08-21 10:22:51,373 - WARNING - Failed authentication for wettenhj from 1.2.3.4
2015-08-21 10:22:51,374 - INFO - Auth rejected (keyboard-interactive).
2015-08-21 10:22:57,466 - INFO - Successful authentication for wettenhj from 1.2.3.4
2015-08-21 10:22:57,466 - INFO - Auth granted (keyboard-interactive).
2015-08-21 10:25:25,209 - INFO - Connection requested from 5.6.7.8
2015-08-21 10:25:25,270 - INFO - Connected (version 2.0, client check_ssh_1.5)
```

### CODE REVIEW

**Comment by grischa** [comment]
Logging is great, but please integrate it with the Django logging framework.
https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/logging_middleware.py

**Comment by wettenhj** [comment]
@grischa, yes, it would be nice to integrate it with the logging middleware.

Would you like me to add sftpd.log to settings_changeme.py (along with tardis.log and request.log) and use it in logging_middleware.py?

Or would you prefer the logs I'm proposing to go in tardis.log?

**Comment by grischa** [comment]
A new file is fine. Maybe add 'sftp' to the 'loggers' setting?
Also, see my Slack comment about fail2ban compatibility.

**Comment by wettenhj** [comment]
@grischa, are you sure that the middleware stuff is called by Django management commands like sftp? The Django docs say "Middleware is a framework of hooks into Django’s request/response processing."

**Pull request closed without merging**
