### PR TITLE
A read_only=True StorageBoxAttribute can be used to indicate that

### PR DESCRIPTION
**Pull request by wettenhj**
MyTardis shouldn't try to modify or delete files in that box.

### CODE REVIEW

**Comment by grischa** [comment]
Read only is different to no-delete, it implies no writing.
I suggest a different name and comparison to an actual value, e.g. `value.lower() == 'true'`

**Comment by grischa** [comment]
or maybe even better to use `can_delete` and set it to `'False'` in your case.

**Comment by wettenhj** [comment]
@grischa, thanks for commenting on this.

Yes, immediately after submitting the pull request, I realized that "read_only" also implies that MyTardis shouldn't write to the storage box, yet I hadn't implemented functionality for preventing writes.

In this case - allowing MyTardis to temporarily access my account on an HPC machine as a "receiving" storage box, I don't want MyTardis to write to my directory, so "read_only" is probably a good description of what I want.

But if you think that isolating the can_delete functionality would be better, I can work with that.  I do prefer "can_delete" over "dont_delete".  "Don't delete" sounds like a double negative.

**Comment by grischa** [comment]
addressed in #569 and #572

**Pull request closed without merging**
