### PR TITLE
Rendering tabular data in datafile parameters from JSON

### PR DESCRIPTION
**Pull request by wettenhj**
Not really expecting this to get merged immediately.  Just creating the pull request to invite comments on this approach.

### CODE REVIEW

**Comment by grischa** [comment]
What kind of data are you rendering this way? Got an example you could post here?

**Comment by wettenhj** [comment]
```
{
    "thead": [
        {
            "$PnN": "Parameter\n($PnN)"
        },
        {
            "$PnS": "Stain\n($PnS)"
        },
        {
            "$PnR": "Range\n($PnR)"
        },
        {
            "$PnB": "Bits\n($PnB)"
        },
        {
            "$PnE": "Decades\n($PnE)"
        },
        {
            "$PnG": "Gain\n($PnG)"
        },
        {
            "$PnV": "Voltage\n($PnV)"
        }
    ],
    "tbody": [
        {
            "$PnN": "FSC-A",
            "$PnB": "32",
            "$PnG": "1",
            "$PnE": "0,0",
            "$PnR": "262144",
            "$PnS": " "
        },
        {
            "$PnN": "SSC-A",
            "$PnB": "32",
            "$PnG": "1",
            "$PnE": "0,0",
            "$PnR": "262144",
            "$PnS": " "
        },
        {
            "$PnN": "PE-A",
            "$PnB": "32",
            "$PnG": "1",
            "$PnE": "0,0",
            "$PnR": "300000",
            "$PnS": " "
        },
        {
            "$PnN": "PerCP-Cy5-5-A",
            "$PnB": "32",
            "$PnG": "1",
            "$PnE": "0,0",
            "$PnR": "300000",
            "$PnS": "CD8a"
        },
        {
            "$PnN": "PE-Cy7-A",
            "$PnB": "32",
            "$PnG": "1",
            "$PnE": "0,0",
            "$PnR": "300000",
            "$PnS": " "
        },
        {
            "$PnN": "APC-Cy7-A",
            "$PnB": "32",
            "$PnG": "1",
            "$PnE": "0,0",
            "$PnR": "300000",
            "$PnS": " "
        },
        {
            "$PnN": "Time",
            "$PnB": "32",
            "$PnG": "12.5",
            "$PnE": "0,0",
            "$PnR": "2048",
            "$PnS": " "
        }
    ]
}
```
rendered-fcs-table

**Comment by grischa** [comment]
Thoughts, @pansapiens?

**Comment by grischa** [comment]
Done in https://github.com/mytardis/mytardis/pull/475

**Pull request closed without merging**
