### PR TITLE
only copy verified files

### PR DESCRIPTION
**Pull request by grischa**
should solve #447. Does it, @wettenhj ?

### CODE REVIEW

**Comment by wettenhj** [comment]
If you only copy verified files, then you are implying that it is a good idea to run verify_dfo on files in temporary receiving boxes.  But I don't think it is a good idea to check anything more than the file size of files in temporary storage boxes.  Sometimes I have my verify_dfos task running every 2 minutes or more often, and a large data file could take 30 minutes to upload.  I don't really want MyTardis to be trying to verify the partial upload every couple of minutes and have my logs filled with verification errors.  Now that verify checks sizes before checksums, it's no longer an issue of wasting computational resources (for calculating checksums), just an issue of filling logs with errors, which are not really errors in my opinion.

**Comment by grischa** [comment]
I think the idea is that we check the files at every step of the way.
I have no problem with logging verification issues only to debug by default, if that's the only reason not to verify.

**Comment by wettenhj** [comment]
Regarding logging, I would consider use of warnings a lot better than errors for failed verifications of uploads still in progress.  I suppose you could use logger.debug as you suggest.

That's not the only reason not to verify - it's also that for large files, calculating checksums can be time-consuming, so users have to wait twice as long to be able to access their verified files in MyTardis if they have to be verified in their temporary storage box as well as their final location.

**Comment by wettenhj** [comment]
There could be a setting for this, along with REQUIRE_DATAFILE_CHECKSUMS etc. if you think some MyTardis deployments would want to always verify both in temporary storage boxes and in the final storage box, whilst other deployments might just want the datafiles to appear verified in their final location as soon as possible.

**Comment by grischa** [comment]
The file is already available for download once it is verified in the temporary box. It is available quicker this way as the copy does not have to complete first

**Comment by wettenhj** [comment]
@grischa wrote "The file is already available for download once it is verified in the temporary box". 

Are you sure?  The DataFile model's verified method looks like it only returns True if all file_objects are verified, not just one of them: 

https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/models/datafile.py#L320

And the datafile_list template currently only allows downloads if datafile.verified is True:

https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/templates/tardis_portal/ajax/datafile_list.html#L78

**Comment by grischa** [comment]
Oh, my bad. I got confused because this is the way it is going to work with some new code I have in another branch. I'll merge it soon, then it will work this way.

**Comment by wettenhj** [comment]
No worries!  :smile:

**Pull request merged**
