### PR TITLE
Proposal: More flexible special character handling in TARs and SFTP

### PR DESCRIPTION
**Pull request by wettenhj**
There are various places where urllib.quote is used with safe='', implying that no characters are safe to leave unencoded, but as mentioned in https://github.com/mytardis/mytardis/issues/819, some characters like spaces are actually safe for file paths within TARs and SFTP views.

The aim of the pull request is to:

1. Add flexibility to tardis/default_settings/downloads.py, so that MyTardis admins can specify which characters they consider to be safe for file paths in TARs and SFTP views.

2. Encourage more use of the "ARCHIVE_FILE_MAPPERS" (which I propose renaming to "DOWNLOAD_PATH_MAPPERS") in both the TAR downloads and the SFTP view.  Using the default ("deep-storage") mapper is nice because it can be configured in settings.py, unlike the hard-coded sanitise_name and dirname_with_id methods in tardis/tardis_portal/util.py

3. Make tardis/tardis_portal/download.py's make_mapper method (formerly _make_mapper) accessible from outside the download.py module, i.e. in the sftp.py module.

While checking that I didn't break any PEP8 stuff in the files I modified, I found some existing PEP8 issues (e.g. lines longer than 80 characters) which I fixed.

REFERENCES

https://kb.acronis.com/content/39790
https://support.apple.com/en-au/HT202808
http://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names
http://stackoverflow.com/questions/2021624/string-sanitizer-for-filename
https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

### CODE REVIEW

**Comment by wettenhj** [comment]
I didn't word this very well: "Using the default ("deep-storage") mapper is nice because it can be configured in settings.py".  Mappers are configurable within upgrading the MyTardis software, but you can't change the default ("deep-storage") mapper without modifying the MyTardis sofware - you can however use it as a template to create your own mapper.

**Comment by grischa** [comment]
This is great, thanks @wettenhj 
However, I think it doesn't go far enough in terms of updating how we present files. I'm not really keen on adding more to the mess that is file mapping right now, even if what you add is good.
I'm going to work out a file mapping framework that incorporates these features and removes the old stuff

**Comment by wettenhj** [comment]
@grischa, thanks for the feedback.  I'm very happy for you to work on a more sophisticated file mapping framework.  Regarding your comment that "it doesn't go far enough", I agree - I tried to limit the number of changes in the initial PR, so it was easier to understand.

Some further changes I would like us to consider in this area:

1. I dislike the term "organization" when referring to the way files are organized in an archive.  My PR renamed the DEFAULT_ARCHIVE_ORGANIZATION setting to DEFAULT_PATH_MAPPER, but "organization" appears in lots of other places in the code and in the templates.

2. Where possible, I would like appending the dataset ID and experiment ID to dataset and experiment folders to be optional, so that in cases where there are no clashes from duplicate folder names, the original file/folder structure can be reconstructed exactly.  I'm not sure how this should work for duplicates, e.g. maybe only add the unique ID to the end of duplicate folder names?

3. I would like to reduce the number of places in the code where we convert spaces to underscores and where we call urllib.quote.  Can we reuse code more efficiently?

4. Perhaps outside the scope of this PR, but I would like to test whether the latest version of the macOS Archive Utility can open streamed ZIP files without size headers.  ZIPs are still more user-friendly to Windows users than TARs, so it would be great if MyTardis could support them.

**Comment by grischa** [comment]
@wettenhj Yeah, agree mostly. Here are some comments, while I still finish my framework:
1. I agree about naming. My suggested new structure will move around a few things, so we can revisit naming after I post it.
2. I had the same thought, add ids only where required
3. The new framework will reduce the number of places where file objects are mapped to paths to 1, that includes any string escaping etc, see 4.
4. Zip would be great, agreed. The aim here is to make sure compression and archiving format are a completely separate concern and any method will result in the same output. So, both zip and tar and also sftp and eventually the webpage will use the same mechanism to generate paths/trees from objects

**Comment by grischa** [comment]
Going to accept this for now. It's not ideal but getting the better solution ready will take too long and it's better not to rush it as well.
Here is the branch where I've been working on an improved data organisation layer to be used by all user-side views on the data: https://github.com/grischa/mytardis/tree/data-organisation

**Comment by wettenhj** [comment]
Thanks @grischa, I agree that more work needs to be done on this.   Hopefully this first step won't make subsequent steps more difficult.  And hopefully no-one is using a non-standard ARCHIVE_FILE_MAPPERS setting which clashes with this change.

**Pull request merged**
