### PR TITLE
Proposal: BDD tests using behave and phantomjs

### PR DESCRIPTION
**Pull request by grischa**
MyTardis tests currently consists only of unit and unit-like tests.
Any code change still requires a manual run of runserver and visual inspection of the template rendering.
Web UIs can be tested automatically though, and this is a basic implementation of such tests.

Run tests with `docker-compose -f docker-test.yml run -e TEST_TYPE=behave test` or `./test.py behave`.

### CODE REVIEW

**Comment by nrmay** [comment]
Where was the proposal to use behave and phantomjs for BDD?

**Comment by jasonrig** [comment]
@grischa, it's probably a good idea to fix the `MEDIA_URL` issue in `urls.py` in a separate PR, so that this discussion can happen without a bug staying longer than it needs to.

@nrmay, the title has been updated. Could you kick off discussion of alternative approaches and their merits?

**Comment by grischa** [comment]
@nrmay Any new comments on this? Would like to add this soon. Thanks

**Comment by grischa** [comment]
@nrmay sorry, I forgot to comment on the existing Jasmine tests. They don't really test anything, there are four simple tests that have not been run automatically, and have not been updated for several years. https://github.com/mytardis/mytardis/blob/develop/tardis/tardis_portal/tests/jasmine/spec/main.js

I would remove the Jasmine tests and focus on this new solution

**Comment by nrmay** [comment]
@grischa @jasonrig  @ianedwardthomas - BDD and web UI testing is a good idea and the correct choice of tools will help us document the functionality. Our preference is for **Lettuce**, which the python flavour of **Cucumber**. We have already used this framework in several systems and so it would make it easy for us to help build a more extensive set of MyTardis tests. See the following sites for more information and examples: 

- http://lettuce.it/index.html
- http://www.re-cycledair.com/integration-testing-with-django-and-lettuce-getting-started
- http://cilliano.com/2011/02/07/django-bdd-with-lettuce-and-splinter.html
- http://kokoko.fluxionary.net/testing-django-part-2-lettuce/

Regarding a framework to drive the browser: we've used **Selenium**, which is a mature toolset that has good support across browsers (http://www.seleniumhq.org/). However, we're less set on this as a solution, as there may be better frameworks. As long as they provide good cross-browser support, and we don't have multiple frameworks hanging around in the MyTardis source code (i.e. we remove the jasmine tests).

**Comment by grischa** [comment]
Thanks for your input @nrmay. I had a look at Lettuce and it looks to be pretty much the same as behave once it is set up. The main difference for implementing tests is the naming of the test decorator/function and that `world` is called `context`.
Since I don't have time to change this and it works as is, I suggest we use this solution.

Selenium is used by splinter internally. I chose PhantomJS for headless automatic tests here. However, anyone can install and use the chromedriver for visible tests. I added documentation for that, too.

**Comment by nrmay** [comment]
@grischa So why is Behave the best solution for MyTardis?

**Comment by wettenhj** [comment]
@nrmay, I don't think merging a pull request into develop should require ironclad proof that it is the "best solution".  One of the benefits of version control is that if we merge something like Behave tests and then we find a better solution, we can easily determine what was changed by that merge and roll back the changes if necessary.  If you think you could submit a pull request for adding MyTardis tests using Lettuce / Cucumber / Selenium very soon, then we could wait and compare the two pull requests.  But if you are not able to do that any time soon, then it might make sense to merge @grischa's pull request, and consider improving on it later.

**Comment by nrmay** [comment]
@wettenhj re: version control and reversing commits. This sounds good in principle, but typically does not work in practice --- especially when applied to architectural decisions (which by definition are hard to change). More anon...

**Comment by wettenhj** [comment]
@grischa, thanks for updating this PR to the latest develop branch!  And thanks for the PR - having tests which go beyond the Python code and across the HTML / Javascript is a great step forward!  @nrmay, thanks for sharing the info about Lettuce and Selenium!

**Pull request merged**
